import React from 'react';
import { ReactFlowProvider } from '@xyflow/react';
import { WorkflowCanvas } from '@/components/admin/workflows/WorkflowCanvas';
import { NodePalette } from '@/components/admin/workflows/panels/NodePalette';
import { NodeInspector } from '@/components/admin/workflows/panels/NodeInspector';
import { Button } from '@/components/ui/Button';
import { ArrowLeft, Save, Play } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useEffect } from 'react';
import { useWorkflowStore } from '@/components/admin/workflows/WorkflowStore';
import { WorkflowService } from '@/services/WorkflowService';
import { toast } from 'sonner';

import { WorkflowTestModal } from '@/components/admin/workflows/WorkflowTestModal';

const WorkflowBuilderPage: React.FC = () => {
    const navigate = useNavigate();
    const { id } = useParams();
    const [isTestModalOpen, setIsTestModalOpen] = React.useState(false);
    const {
        workflowId,
        workflowName,
        triggerType,
        triggerConfig,
        isActive,
        nodes,
        edges,
        setWorkflow,
        reset
    } = useWorkflowStore();

    useEffect(() => {
        if (id) {
            const loadWorkflow = async () => {
                try {
                    const toastId = toast.loading('Carregando workflow...');
                    const { workflow, nodes, edges } = await WorkflowService.getWorkflow(id);
                    setWorkflow(workflow as any, nodes as any, edges);
                    toast.dismiss(toastId);
                } catch (error) {
                    console.error('Error loading workflow:', error);
                    toast.error('Erro ao carregar workflow.');
                    navigate('/settings/workflows');
                }
            };
            loadWorkflow();
        } else {
            reset();
        }
    }, [id, setWorkflow, reset, navigate]);

    const handleSave = async () => {
        try {
            const loadingToast = toast.loading('Salvando workflow...');

            // 1. Map React Flow Nodes to DB Nodes
            const dbNodes = nodes.map(node => ({
                id: node.id, // Use the UUID generated by React Flow
                node_key: node.data.label as string, // Or generate a slug
                node_type: node.type,
                action_type: node.data.action_type,
                action_config: node.data.action_config,
                condition_config: node.data.condition_config,
                wait_config: node.data.wait_config,
                position_x: Math.round(node.position.x),
                position_y: Math.round(node.position.y)
            }));

            // 2. Map React Flow Edges to DB Edges
            const dbEdges = edges.map((edge, index) => ({
                id: edge.id,
                source_node_id: edge.source,
                target_node_id: edge.target,
                condition: edge.data?.condition,
                label: edge.label,
                edge_order: index // Simple ordering based on array position
            }));

            // 3. Prepare Workflow Data
            const workflowData = {
                id: workflowId || undefined,
                name: workflowName,
                trigger_type: triggerType as any,
                trigger_config: triggerConfig,
                is_active: isActive
            };

            // 4. Call Service
            const savedId = await WorkflowService.saveWorkflow(workflowData, dbNodes, dbEdges);

            // 5. Update Store with saved ID (if new)
            if (!workflowId) {
                // Ideally we should reload the full workflow to get fresh state, 
                // but for now just setting the ID is enough to prevent duplicate creates
                useWorkflowStore.setState({ workflowId: savedId });
            }

            toast.dismiss(loadingToast);
            toast.success('Workflow salvo com sucesso!');

        } catch (error) {
            console.error('Failed to save workflow:', error);
            toast.error('Erro ao salvar workflow. Tente novamente.');
        }
    };

    return (
        <div className="h-full w-full flex flex-col bg-slate-50 overflow-hidden">
            {/* Header */}
            <header className="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-6 z-20 shadow-sm">
                <div className="flex items-center gap-4">
                    <Button variant="ghost" size="icon" onClick={() => navigate('/settings/workflows')}>
                        <ArrowLeft className="w-5 h-5 text-slate-500" />
                    </Button>
                    <div>
                        <h1 className="text-lg font-semibold text-slate-900">Editor de Workflow</h1>
                        <p className="text-xs text-slate-500">Editando "{workflowName}"</p>
                    </div>
                </div>

                <div className="flex items-center gap-2">
                    <Button
                        variant="outline"
                        onClick={() => setIsTestModalOpen(true)}
                        disabled={!workflowId} // Only allow testing if saved
                    >
                        <Play className="w-4 h-4 mr-2" />
                        Testar
                    </Button>
                    <Button
                        className="bg-indigo-600 hover:bg-indigo-700 text-white gap-2"
                        onClick={handleSave}
                    >
                        <Save className="w-4 h-4" /> Salvar
                    </Button>
                </div>
            </header>

            {/* Main Content */}
            <div className="flex-1 flex overflow-hidden relative">
                <ReactFlowProvider>
                    <div className="flex-1 relative">
                        <NodePalette />
                        <WorkflowCanvas />
                    </div>
                    <NodeInspector />
                </ReactFlowProvider>
            </div>

            {/* Test Modal */}
            {workflowId && (
                <WorkflowTestModal
                    isOpen={isTestModalOpen}
                    onClose={() => setIsTestModalOpen(false)}
                    workflowId={workflowId}
                />
            )}
        </div>
    );
};

export default WorkflowBuilderPage;
